//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace orangeBrowser_Kai.settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class ShortCutKey : global::System.Configuration.ApplicationSettingsBase {
        
        private static ShortCutKey defaultInstance = ((ShortCutKey)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ShortCutKey())));
        
        public static ShortCutKey Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+W")]
        public global::System.Windows.Forms.Keys Window_Close {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Window_Close"]));
            }
            set {
                this["Window_Close"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public global::System.Windows.Forms.Keys Window_Open_Settings {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Window_Open_Settings"]));
            }
            set {
                this["Window_Open_Settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public global::System.Windows.Forms.Keys Window_Open_DownloadStatus {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Window_Open_DownloadStatus"]));
            }
            set {
                this["Window_Open_DownloadStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public global::System.Windows.Forms.Keys UrlBar_SelectAll {
            get {
                return ((global::System.Windows.Forms.Keys)(this["UrlBar_SelectAll"]));
            }
            set {
                this["UrlBar_SelectAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F8")]
        public global::System.Windows.Forms.Keys UrlBar_Paste {
            get {
                return ((global::System.Windows.Forms.Keys)(this["UrlBar_Paste"]));
            }
            set {
                this["UrlBar_Paste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+R")]
        public global::System.Windows.Forms.Keys Browser_Reload {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Browser_Reload"]));
            }
            set {
                this["Browser_Reload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+Home")]
        public global::System.Windows.Forms.Keys Browser_Home {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Browser_Home"]));
            }
            set {
                this["Browser_Home"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+T")]
        public global::System.Windows.Forms.Keys Alert_Time {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Alert_Time"]));
            }
            set {
                this["Alert_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+D")]
        public global::System.Windows.Forms.Keys Nico_Download {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Nico_Download"]));
            }
            set {
                this["Nico_Download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+D")]
        public global::System.Windows.Forms.Keys Nico_Reserve {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Nico_Reserve"]));
            }
            set {
                this["Nico_Reserve"] = value;
            }
        }
    }
}
